language: python
python: "3.5.5"
services:
  - postgresql
addons:
    postgresql: "9.6"

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis.git
  - cd osis
  - git checkout dev
  - git pull origin dev
  - git submodule init
  - git submodule update
  - pip install -r requirements.txt
  - rm -Rf partnership
  - ln -s $PROJECT_DIR partnership
  - cp partnership/.coveragerc .

before_script:
  - cp .env.example .env
  - echo 'INSTALLED_APPS += ("partnership",)' >> backoffice/settings/local.py
  - echo 'APPS_TO_TEST += ("partnership",)' >> backoffice/settings/local.py
  - echo 'LOCALE_PATHS = [BASE_DIR + "/partnership/locale"]' >> backoffice/settings/local.py
  - echo >> .env
  - echo "POSTGRES_USER = 'postgres'" >> .env
  - echo "POSTGRES_PASSWORD = ''" >> .env
  - python3 manage.py compilemessages
  - psql -c 'create database osis_local;' -U postgres

script:
  - coverage run manage.py test --exclude-tag=selenium partnership

after_success:
 - pip install python-coveralls
 - coveralls --base_dir /home/travis/build/uclouvain/osis-partnership/
