openapi: "3.0.2"
info:
  version: 1.0.0
  title: OSIS Partnerships
components:
  schemas:
    ValueLabel:
      required:
        - id
        - label
      properties:
        id:
          type: string
        label:
          type: string
    Funding:
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
    Contact:
      properties:
        name:
          type: string
        email:
          type: string
          format: email
    Partner:
      properties:
        name:
          type: string
        partner_entity:
          type: string
        city:
          type: string
        education_field:
          type: string
        ucl_university:
          type: string
        ucl_university_labo:
          type: string
        supervisor:
          type: string
        mobility_type:
          type: string
          enum:
            - student
            - studies
            - 'short_term'
            - training
        status:
          type: object
          properties:
            valid:
              type: boolean
            last_valid:
              type: string
        out_education_level:
          type: string
        out_entity:
          type: string
        out_university_offer:
          type: string
        out_contact:
          description: UCL contact
          $ref: '#/components/schemas/Contact'
        out_portal:
          type: string
          format: uri
        out_funding:
          $ref: '#/components/schemas/Funding'
        out_partner_contact:
          description: Contact in partner institution
          $ref: '#/components/schemas/Contact'
        in_contact:
          $ref: '#/components/schemas/Contact'
        in_portal:
          type: string
          format: uri
        staff_contact_name:
          description: UCL contact
          type: string
        staff_partner_contact:
          description: Contact in partner institution
          $ref: '#/components/schemas/Contact'
        staff_funding:
          $ref: '#/components/schemas/Funding'
    Partners:
      type: array
      items:
        $ref: "#/components/schemas/Partner"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    limit:
      name: limit
      in: query
      description: How many items to return at one time
      maximum: 100
      default: 25
      schema:
        type: integer
        format: int32
    offset:
      name: offset
      in: query
      schema:
        description: The initial index from which to return the results.
        type: integer
    ordering:
      name: ordering
      in: query
      description: The ordering of the items returned
      default: partner
      schema:
        type: string
        enum:
          - partner
          - country_en
          - city
          - ucl_university
          - subject_area
    continent:
      name: continent
      in: query
      description:
      schema:
        type: string
    country:
      name: country
      in: query
      description:
      schema:
        type: string
    city:
      name: city
      in: query
      description:
      schema:
        type: string
    partner:
      name: partner
      in: query
      description: The id of the partner
      schema:
        type: string
    ucl_university:
      name: ucl_university
      in: query
      description: The id of the faculty
      schema:
        type: string
    ucl_university_labo:
      name: ucl_university_labo
      in: query
      description: The id of the faculty's school
      schema:
        type: string
    campus:
      name: campus
      in: query
      description:
      schema:
        type: string
    supervisor:
      name: supervisor
      in: query
      description: The id of the supervisor
      schema:
        type: string
    education_field:
      name: education_field
      in: query
      description: The id of the education field
      schema:
        type: string
    mobility_type:
      name: mobility_type
      in: query
      description:
      schema:
        type: string
        enum:
          - student
          - staff
    funding:
      name: funding
      in: query
      description:
      schema:
        type: string
        enum:
          - erasmus
          - belgica
          - fame-mercator
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /configuration:
    get:
      summary: List all possible values for parameters on other endpoints
      tags:
        - partners
      responses:
        '200':
          description: The list of possible values for parameters on other endpoints
          content:
            application/json:
              schema:
                properties:
                  continent:
                    type: array
                    items:
                      type: string
                  country:
                    type: array
                    items:
                      type: string
                  city:
                    type: array
                    items:
                      type: string
                  partner:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  ucl_university:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  ucl_university_labo:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  campus:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  supervisor:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  education_field:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
  /partners:
    get:
      summary: List all partners
      tags:
        - partners
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/ordering'
        - $ref: '#/components/parameters/continent'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/city'
        - $ref: '#/components/parameters/partner'
        - $ref: '#/components/parameters/ucl_university'
        - $ref: '#/components/parameters/ucl_university_labo'
        - $ref: '#/components/parameters/campus'
        - $ref: '#/components/parameters/supervisor'
        - $ref: '#/components/parameters/education_field'
        - $ref: '#/components/parameters/mobility_type'
        - $ref: '#/components/parameters/funding'
      responses:
        '200':
          description: A paged array of partners
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partners"
        '400':
          $ref: '#/components/responses/BadRequest'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"