openapi: "3.0.0"
servers:
 - url: https://{environment}.osis.uclouvain.be/api/v1/partnerships/
   variables:
     environment:
       default: dev
       enum:
         - dev # Development server
         - qa # Staging server
         - test # Test server
 - url: https://osis.uclouvain.be/api/v1/partnerships/
   description: Production server
info:
  version: 1.0.0
  title: OSIS Partnerships
components:
  schemas:
    ValueLabel:
      type: object
      required:
        - id
        - label
      properties:
        id:
          type: string
        label:
          type: string
    Funding:
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
    Contact:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
    Partner:
      type: object
      properties:
        name:
          type: string
        erasmus_code:
          type: string
        partner_entity:
          type: string
        city:
          type: string
        country:
          type: string
    Partnership:
      type: object
      properties:
        partner:
          $ref: '#/components/schemas/Partner'
        education_field:
          type: string
        ucl_university:
          type: string
        ucl_university_labo:
          type: string
        supervisor:
          type: string
        mobility_type:
          type: string
          enum:
            - student
            - studies
            - 'short_term'
            - training
            - staff
        status:
          type: object
          properties:
            valid:
              type: boolean
            last_valid:
              type: string
        out_education_level:
          type: string
        out_entity:
          type: string
        out_university_offer:
          type: string
        out_contact:
          description: UCL contact
          $ref: '#/components/schemas/Contact'
        out_portal:
          type: string
          format: uri
        out_funding:
          $ref: '#/components/schemas/Funding'
        out_partner_contact:
          description: Contact in partner institution
          $ref: '#/components/schemas/Contact'
        in_contact:
          $ref: '#/components/schemas/Contact'
        in_portal:
          type: string
          format: uri
        staff_contact_name:
          description: UCL contact
          type: string
        staff_partner_contact:
          description: Contact in partner institution
          $ref: '#/components/schemas/Contact'
        staff_funding:
          $ref: '#/components/schemas/Funding'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    limit:
      name: limit
      in: query
      description: How many items to return at one time
      schema:
        type: integer
        format: int32
        maximum: 100
        default: 25
    offset:
      name: offset
      in: query
      schema:
        description: The initial index from which to return the results.
        type: integer
    ordering:
      name: ordering
      in: query
      description: The ordering of the items returned
      schema:
        type: string
        default: partner
        enum:
          - partner
          - country_en
          - city
          - ucl_university
          - subject_area
    continent:
      name: continent
      in: query
      schema:
        type: string
    country:
      name: country
      in: query
      schema:
        type: string
    city:
      name: city
      in: query
      schema:
        type: string
    partner:
      name: partner
      in: query
      description: The id of the partner
      schema:
        type: string
    ucl_university:
      name: ucl_university
      in: query
      description: The id of the faculty
      schema:
        type: string
    ucl_university_labo:
      name: ucl_university_labo
      in: query
      description: The id of the faculty's school
      schema:
        type: string
    supervisor:
      name: supervisor
      in: query
      description: The id of the supervisor
      schema:
        type: string
    education_field:
      name: education_field
      in: query
      description: The id of the education field
      schema:
        type: string
    mobility_type:
      name: mobility_type
      in: query
      schema:
        type: string
        enum:
          - student
          - staff
    funding:
      name: funding
      in: query
      schema:
        type: string
        enum:
          - erasmus
          - belgica
          - fame-mercator
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /partnerships/configuration/:
    get:
      summary: List all possible values for parameters on other endpoints
      tags:
        - partners
      responses:
        '200':
          description: The list of possible values for parameters on other endpoints
          content:
            application/json:
              schema:
                properties:
                  continents:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        countries:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              iso_code:
                                type: string
                  partners:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  ucl_universities:
                    type: object
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                      ucl_university_labos:
                        type: array
                        items:
                          $ref: '#/components/schemas/ValueLabel'
                  supervisors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  education_fields:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
  /partnerships/partners/:
    get:
      summary: List all partners
      tags:
        - partners
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/ordering'
        - $ref: '#/components/parameters/continent'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/city'
        - $ref: '#/components/parameters/partner'
        - $ref: '#/components/parameters/ucl_university'
        - $ref: '#/components/parameters/ucl_university_labo'
        - $ref: '#/components/parameters/supervisor'
        - $ref: '#/components/parameters/education_field'
        - $ref: '#/components/parameters/mobility_type'
        - $ref: '#/components/parameters/funding'
      responses:
        '200':
          description: A paged array of partners
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                  previous:
                    type: string
                    format: uri
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Partner"
        '400':
          $ref: '#/components/responses/BadRequest'
  /partnerships/:
    get:
      summary: List all partners
      tags:
        - partners
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/ordering'
        - $ref: '#/components/parameters/continent'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/city'
        - $ref: '#/components/parameters/partner'
        - $ref: '#/components/parameters/ucl_university'
        - $ref: '#/components/parameters/ucl_university_labo'
        - $ref: '#/components/parameters/supervisor'
        - $ref: '#/components/parameters/education_field'
        - $ref: '#/components/parameters/mobility_type'
        - $ref: '#/components/parameters/funding'
      responses:
        '200':
          description: A paged array of partnerships
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                  previous:
                    type: string
                    format: uri
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Partnership"
        '400':
          $ref: '#/components/responses/BadRequest'