# Generated by Django 3.2.21 on 2023-10-19 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0004_auto_20231011_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('EPLUS-EDU-HEI', 'Higher education institution (tertiary level)'), ('EPLUS-EDU-GEN-PRE', 'School/Institute/Educational centre - General education (pre-primary level)'), ('EPLUS-EDU-GEN-PRI', 'School/Institute/Educational centre - General education (primary level)'), ('EPLUS-EDU-GEN-SEC', 'School/Institute/Educational centre - General education (secondary level)'), ('EPLUS-EDU-VOC-SEC', 'School/Institute/Educational centre - Vocational Training (secondary level)'), ('EPLUS-EDU-VOC-TER', 'School/Institute/Educational centre - Vocational Training (tertiary level)'), ('EPLUS-EDU-ADULT', 'School/Institute/Educational centre - Adult education'), ('EPLUS-BODY-PUB-NAT', 'National Public body'), ('EPLUS-BODY-PUB-REG', 'Regional Public body'), ('EPLUS-BODY-PUB-LOC', 'Local Public body'), ('EPLUS-ENT-SME', 'Small and medium sized enterprise'), ('EPLUS-ENT-LARGE', 'Large enterprise'), ('EPLUS-NGO', 'Non-governmental organisation/association/social enterprise'), ('EPLUS-FOUND', 'Foundation'), ('EPLUS-SOCIAL', 'Social partner or other representative of working life (chambers of commerce, trade union, trade association)'), ('EPLUS-RES', 'Research Institute/Centre'), ('EPLUS-YOUTH-COUNCIL', 'National Youth Council'), ('EPLUS-ENGO', 'European NGO'), ('EPLUS-NET-EU', 'EU-wide network'), ('EPLUS-YOUTH-GROUP', 'Group of young people active in youth work'), ('EPLUS-EURO-GROUP-COOP', 'European grouping of territorial cooperation'), ('EPLUS-BODY-ACCRED', 'Accreditation, _(certification or qualification body'), ('EPLUS-BODY-CONS', 'Counsellzing body'), ('EPLUS-INTER', 'International organisation under public law'), ('EPLUS-SPORT-PARTIAL', 'Organisation or association representing (parts of) the sport sector'), ('EPLUS-SPORT-FED', 'Sport federation'), ('EPLUS-SPORT-LEAGUE', 'Sport league'), ('EPLUS-SPORT-CLUB', 'Sport club'), ('OTH', 'Other')], help_text='mandatory_if_not_pic_ies', max_length=255, null=True, verbose_name='partner_contact_type'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[('GENERAL', 'Accord general de collaboration'), ('MOBILITY', 'Partenariat de mobilite'), ('COURSE', 'Partenariat de co-organisation de formation'), ('DOCTORATE', 'Partenariat de co-organisation de doctorat'), ('PROJECT', 'Projet finance')], db_index=True, max_length=255, verbose_name='partnership_type'),
        ),
        migrations.AlterField(
            model_name='partnershipentitymanager',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GENERAL', 'Accord general de collaboration'), ('MOBILITY', 'Partenariat de mobilite'), ('COURSE', 'Partenariat de co-organisation de formation'), ('DOCTORATE', 'Partenariat de co-organisation de doctorat'), ('PROJECT', 'Projet finance')], max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='partnershipmission',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GENERAL', 'Accord general de collaboration'), ('MOBILITY', 'Partenariat de mobilite'), ('COURSE', 'Partenariat de co-organisation de formation'), ('DOCTORATE', 'Partenariat de co-organisation de doctorat'), ('PROJECT', 'Projet finance')], max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='partnershipsubtype',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GENERAL', 'Accord general de collaboration'), ('MOBILITY', 'Partenariat de mobilite'), ('COURSE', 'Partenariat de co-organisation de formation'), ('DOCTORATE', 'Partenariat de co-organisation de doctorat'), ('PROJECT', 'Projet finance')], max_length=50), size=None),
        ),
    ]
