# Generated by Django 4.2.16 on 2024-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnership", "0007_alter_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="medias",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="partnership.media",
                verbose_name="medias",
            ),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="partnership.contact",
                verbose_name="contacts",
            ),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="medias",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="partnership.media",
                verbose_name="medias",
            ),
        ),
    ]
