# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0295_auto_20180627_1417'),
        ('partnership', '0007_auto_20180703_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnershipyear',
            unique_together=set([('partnership', 'academic_year')]),
        ),
    ]
