# Generated by Django 3.2.25 on 2024-07-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0694_alter_personticketcreation_person'),
        ('partnership', '0007_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='all_student',
            field=models.BooleanField(default=True, help_text='partnership_all_student_help_text', verbose_name='partnership_all_student'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='school_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_reference', to='base.entity'),
        ),
    ]
