# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0008_auto_20180703_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershipyear',
            options={'ordering': ('academic_year__year',)},
        ),
        migrations.RemoveField(
            model_name='partnershipoffer',
            name='state',
        ),
        migrations.AddField(
            model_name='partnershipoffer',
            name='status',
            field=models.CharField(choices=[('waiting', 'status_waiting'), ('validated', 'status_validated'), ('refused', 'status_refused')], default='waiting', max_length=10, verbose_name='status'),
        ),
    ]
