# Generated by Django 4.2.16 on 2025-01-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0008_auto_20240723_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='+', to='partnership.media', verbose_name='medias'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='+', to='partnership.contact', verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='diploma_by_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='+', to='partnership.media', verbose_name='medias'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='supplement_prod_by_ucl',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl_by_partner',
            field=models.CharField(choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnershiprelation', to='partnership.partnership'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='supplement_prod_by_partner',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
    ]
