# Generated by Django 3.2.25 on 2024-07-12 10:29

from django.db import migrations, models
import partnership.models.enums.partnership


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0008_auto_20240711_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='diploma_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Partenaire unique'), ('SEPARED', 'Partenaire séparé'), ('NO_CODIPLOMA', 'Non co-diplômant')], default='UNIQUE', max_length=64),
        ),
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='supplement_production',
            field=models.CharField(choices=[('YES', 'Oui'), ('NO', 'Non'), ('SHARED', 'Partagé')], default='NO', max_length=64),
        ),
    ]
