# Generated by Django 3.2.25 on 2024-07-15 10:01

from django.db import migrations, models
import partnership.models.enums.partnership


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0009_auto_20240712_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='ucl_reference',
            field=models.BooleanField(default=True, help_text='partnership_ucl_reference_help_text', verbose_name='partnership_ucl_reference'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Partenaire unique'), ('SEPARED', 'Partenaire séparé'), ('NO_CODIPLOMA', 'Non co-diplômant')], default='UNIQUE', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='supplement_production',
            field=models.CharField(choices=[('YES', 'Oui'), ('NO', 'Non'), ('SHARED', 'Partagé')], default='NO', max_length=64),
        ),
    ]
