# Generated by Django 4.2.16 on 2025-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0008_alter_partner_medias_alter_partnership_contacts_and_more'),
        ('partnership', '0009_alter_partner_medias_alter_partnership_contacts_and_more'),
    ]

    operations = [
    ]
