# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0010_auto_20180704_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='erasmus_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='erasmus_code'),
        ),
    ]
