# Generated by Django 4.2.16 on 2025-03-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0010_merge_20250109_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='all_student',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='diploma_by_ucl',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='diploma_prod_by_ucl',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='partner_referent',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='supplement_prod_by_ucl',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='ucl_reference',
        ),
        migrations.RemoveField(
            model_name='partnershippartnerrelation',
            name='diploma_prod_by_partner',
        ),
        migrations.RemoveField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl_by_partner',
        ),
        migrations.RemoveField(
            model_name='partnershippartnerrelation',
            name='supplement_prod_by_partner',
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='all_student',
            field=models.BooleanField(blank=True, default=True, verbose_name='all_student'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='diploma_prod_by_ucl',
            field=models.BooleanField(default=False, verbose_name='diploma_prod_by_ucl'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='supplement_prod_by_ucl',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='supplement_prod_by_ucl'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='type_diploma_by_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='type_diploma_by_ucl'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='ucl_reference',
            field=models.BooleanField(blank=True, default=True, verbose_name='ucl_reference'),
        ),
        migrations.CreateModel(
            name='PartnershipPartnerRelationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_diploma_by_partner', models.CharField(blank=True, choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='type_diploma_by_partner')),
                ('diploma_prod_by_partner', models.BooleanField(default=False, verbose_name='diploma_prod_by_partner')),
                ('supplement_prod_by_partner', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='supplement_prod_by_partner')),
                ('partner_referent', models.BooleanField(default=False, verbose_name='partner_referent')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.academicyear', verbose_name='academic_year')),
                ('partnership_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnershiprelation', to='partnership.partnershippartnerrelation')),
            ],
            options={
                'unique_together': {('partnership_relation', 'academic_year')},
            },
        ),
    ]
