# Generated by Django 3.2.25 on 2024-07-16 14:46

from django.db import migrations, models
import django.db.models.deletion
import partnership.models.enums.partnership


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0010_auto_20240715_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='school_reference',
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_referent', to='base.entity'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='all_student',
            field=models.BooleanField(blank=True, default=True, help_text='partnership_all_student_help_text', verbose_name='partnership_all_student'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='ucl_reference',
            field=models.BooleanField(blank=True, default=True, help_text='partnership_ucl_reference_help_text', verbose_name='partnership_ucl_reference'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Partenaire unique'), ('SEPARED', 'Partenaire séparé'), ('NO_CODIPLOMA', 'Non co-diplômant')], default='UNIQUE', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelation',
            name='supplement_production',
            field=models.CharField(choices=[('YES', 'Oui'), ('NO', 'Non'), ('SHARED', 'Partagé')], default='NO', max_length=64),
        ),
    ]
