# Generated by Django 3.2.25 on 2024-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0011_auto_20240716_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnershippartnerrelation',
            old_name='diploma_production',
            new_name='diploma_prod_by_partner',
        ),
        migrations.RemoveField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl',
        ),
        migrations.RemoveField(
            model_name='partnershippartnerrelation',
            name='supplement_production',
        ),
        migrations.AddField(
            model_name='partnership',
            name='diploma_by_ucl',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Partenaire unique'), ('SEPARED', 'Partenaire séparé'), ('NO_CODIPLOMA', 'Non co-diplômant')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='diploma_prod_by_ucl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnership',
            name='supplement_prod_by_ucl',
            field=models.CharField(blank=True, choices=[('YES', 'Oui'), ('NO', 'Non'), ('SHARED', 'Partagé')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='diploma_with_ucl_by_partner',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Partenaire unique'), ('SEPARED', 'Partenaire séparé'), ('NO_CODIPLOMA', 'Non co-diplômant')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='supplement_prod_by_partner',
            field=models.CharField(blank=True, choices=[('YES', 'Oui'), ('NO', 'Non'), ('SHARED', 'Partagé')], max_length=64, null=True),
        ),
    ]
