# Generated by Django 4.2.16 on 2025-03-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0011_remove_partnership_all_student_and_more'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='PartnershipYearOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('education_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_educationgroup', to='base.educationgroup')),
                ('educationgroupyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_year_offers', to='base.educationgroupyear', verbose_name='education_group_year')),
                ('partnershipyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_year', to='partnership.partnershipyear', verbose_name='partnership_year')),
            ],
            options={
                'db_table': 'partnership_partnershipyear_offers',
            },
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='offers',
            field=models.ManyToManyField(blank=True, help_text='partnership_year_offers_help_text', related_name='partnerships', through='partnership.PartnershipYearOffers', to='base.educationgroupyear', verbose_name='partnership_year_offers'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name='PartnershipYearOffers',
            name='educationgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_educationgroup', to='base.educationgroup'),
        ),
    ]
