# Generated by Django 4.2.16 on 2025-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0011_remove_partnership_all_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershipyear',
            name='partner_referent',
        ),
        migrations.AddField(
            model_name='partnershippartnerrelationyear',
            name='partner_referent',
            field=models.BooleanField(default=False),
        ),
    ]
