# Generated by Django 4.2.16 on 2025-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0012_remove_partnershipyear_partner_referent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnershippartnerrelationyear',
            old_name='diploma_with_ucl_by_partner',
            new_name='type_diploma_by_partner',
        ),
    ]
