# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0012_auto_20180705_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='address_name_help_text', max_length=255, null=True, verbose_name='name'),
        ),
    ]
