# Generated by Django 4.2.16 on 2025-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0013_rename_diploma_with_ucl_by_partner_partnershippartnerrelationyear_type_diploma_by_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='supplement_prod_by_partner',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='type_diploma_by_partner',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64),
        ),
    ]
