# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 14:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0013_auto_20180705_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='modified',
            new_name='changed',
        ),
        migrations.AddField(
            model_name='partner',
            name='external_id',
            field=models.CharField(blank=True, help_text='to_synchronize_with_epc', max_length=255, null=True, unique=True, verbose_name='external_id'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships', to='partnership.PartnerEntity', verbose_name='partner_entity'),
        ),
    ]
