# Generated by Django 4.2.16 on 2025-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0014_alter_partnershippartnerrelationyear_supplement_prod_by_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='diploma_prod_by_partner',
            field=models.BooleanField(default=False, verbose_name='diploma_prod_by_partner'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='partner_referent',
            field=models.BooleanField(default=False, verbose_name='partner_referent'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='supplement_prod_by_partner',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='supplement_prod_by_partner'),
        ),
        migrations.AlterField(
            model_name='partnershippartnerrelationyear',
            name='type_diploma_by_partner',
            field=models.CharField(blank=True, choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='type_diploma_by_partner'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='all_student',
            field=models.BooleanField(blank=True, default=True, verbose_name='all_student'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='diploma_prod_by_ucl',
            field=models.BooleanField(default=False, verbose_name='diploma_prod_by_ucl'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='supplement_prod_by_ucl',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='supplement_prod_by_ucl'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='type_diploma_by_ucl',
            field=models.CharField(choices=[('UNIQUE', 'Unique joint'), ('SEPARED', 'Separed'), ('NO_CODIPLOMA', 'No joint diploma'), ('SHARED', 'Shared')], default='', max_length=64, verbose_name='type_diploma_by_ucl'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='ucl_reference',
            field=models.BooleanField(blank=True, default=True, verbose_name='ucl_reference'),
        ),
    ]
