# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_entities(apps, schema_editor):
    EntityVersion = apps.get_model('base', 'EntityVersion')
    Partnership = apps.get_model('partnership', 'Partnership')
    for partnership in Partnership.objects.all():
        partnership.ucl_university_id = EntityVersion.objects.get(id=partnership.ucl_university_id).entity.id
        if partnership.ucl_university_labo_id is not None:
            partnership.ucl_university_labo_id = EntityVersion.objects.get(id=partnership.ucl_university_labo_id).entity.id



class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0014_auto_20180706_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='ucl_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnerships', to='base.Entity', verbose_name='ucl_university'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='ucl_university_labo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_labo', to='base.Entity', verbose_name='ucl_university_labo'),
        ),
        migrations.RunPython(migrate_entities),
    ]
