# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0295_auto_20180627_1417'),
        ('partnership', '0019_auto_20180711_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='partnership_supervisor'),
        ),
    ]
