# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0020_partnership_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='address_name_help_text', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, help_text='media_file_or_url', null=True, upload_to='medias/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, help_text='media_file_or_url', null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='partner_code'),
        ),
        migrations.AlterField(
            model_name='partnerentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
