# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0021_auto_20180716_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipagreement',
            name='eligible',
            field=models.BooleanField(default=False, verbose_name='eligible'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='changed',
            field=models.DateField(auto_now=True, verbose_name='changed'),
        ),
    ]
