# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0364_auto_20181005_1215'),
        ('partnership', '0028_auto_20180803_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCLManagementEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_in_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('contact_in_url', models.URLField(blank=True, null=True, verbose_name='portal')),
                ('contact_out_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('contact_out_url', models.URLField(blank=True, null=True, verbose_name='portal')),
                ('academic_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='academic_responsible')),
                ('administrative_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='administrative_responsible')),
                ('contact_in_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='contact_in_name')),
                ('contact_out_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='contact_out_name')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity', verbose_name='entity')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity', verbose_name='faculty')),
            ],
        ),
        migrations.AlterModelOptions(
            name='financing',
            options={'ordering': ('academic_year__year',)},
        ),
        migrations.AlterModelOptions(
            name='partnershipagreement',
            options={'ordering': ['-start_academic_year__start_date'], 'verbose_name': 'financing'},
        ),
        migrations.AlterUniqueTogether(
            name='uclmanagemententity',
            unique_together=set([('faculty', 'entity')]),
        ),
    ]
