# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0358_auto_20180921_1059'),
        ('partnership', '0028_auto_20180803_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipYearEducationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PartnershipYearEducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='financing',
            options={'ordering': ('academic_year__year',)},
        ),
        migrations.AlterModelOptions(
            name='partnershipagreement',
            options={'ordering': ['-start_academic_year__start_date'], 'verbose_name': 'financing'},
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='university_offers',
        ),
        migrations.RemoveField(
            model_name='partnershipyear',
            name='education_field',
        ),
        migrations.RemoveField(
            model_name='partnershipyear',
            name='education_level',
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='university_offers',
            field=models.ManyToManyField(blank=True, related_name='partnerships', to='base.EducationGroupYear', verbose_name='university_offers'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='education_fields',
            field=models.ManyToManyField(to='partnership.PartnershipYearEducationField', verbose_name='education_fields'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='education_levels',
            field=models.ManyToManyField(to='partnership.PartnershipYearEducationLevel', verbose_name='education_levels'),
        ),
    ]
