# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0028_auto_20180803_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financing',
            options={'ordering': ('academic_year__year',)},
        ),
        migrations.AlterModelOptions(
            name='partnershipagreement',
            options={'ordering': ['-start_academic_year__start_date'], 'verbose_name': 'financing'},
        ),
    ]
