# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0030_uclmanagemententity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='administrative_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
    ]
