# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0332_auto_20180816_1540'),
        ('partnership', '0031_auto_20180924_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uclmanagemententity',
            name='contact_in',
        ),
        migrations.RemoveField(
            model_name='uclmanagemententity',
            name='contact_out',
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_in_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_in_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_in_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_out_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_out_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.AddField(
            model_name='uclmanagemententity',
            name='contact_out_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EntityVersion'),
        ),
    ]
