# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0031_auto_20181004_0936'),
        ('partnership', '0029_auto_20181005_1835'),
    ]

    operations = [
    ]
