# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-17 10:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0366_auto_20181010_1627'),
        ('partnership', '0032_merge_20181005_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipyeareducationlevel',
            name='education_group_types',
            field=models.ManyToManyField(related_name='partnership_education_levels', to='base.EducationGroupType', verbose_name='education_group_types'),
        ),
        migrations.AlterField(
            model_name='partnershipagreement',
            name='end_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnership_agreements_end', to='base.AcademicYear', verbose_name='end_academic_year'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text='partnership_year_entities_help_text', related_name='_partnershipyear_entities_+', to='base.Entity', verbose_name='partnership_year_entities'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='offers',
            field=models.ManyToManyField(blank=True, help_text='partnership_year_offers_help_text', related_name='partnerships', to='base.EducationGroupYear', verbose_name='partnership_year_offers'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_managements', to='base.Entity', verbose_name='entity'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_managements', to='base.Entity', verbose_name='faculty'),
        ),
    ]
