# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0032_auto_20180925_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uclmanagemententity',
            old_name='academic_respondent',
            new_name='academic_responsible',
        ),
    ]
