# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0033_auto_20180927_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='academic_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='academic_responsible'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='administrative_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='administrative_responsible'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_in_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_in_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_in_url',
            field=models.URLField(blank=True, null=True, verbose_name='portal'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_out_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_out_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='contact_out_url',
            field=models.URLField(blank=True, null=True, verbose_name='portal'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity', verbose_name='entity'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity', verbose_name='faculty'),
        ),
    ]
