# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0033_auto_20181017_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfiguration',
            name='email_notification_to',
            field=models.EmailField(default='programmes.mobilite@uclouvain.be', max_length=254, verbose_name='partnership_email_notification_to'),
        ),
    ]
