# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0034_auto_20180927_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='ucl_management_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partnership.UCLManagementEntity', verbose_name='ucl_management_entity'),
        ),
    ]
