# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-01 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0035_partnership_ucl_management_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='contacts',
        ),
    ]
