# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0036_remove_partnership_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='ucl_management_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='partnership.UCLManagementEntity', verbose_name='ucl_management_entity'),
        ),
    ]
