# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-06 10:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def remove_unused_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        codename='can_access_partners',
        content_type__app_label='partnership',
        content_type__model='partnership'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0036_auto_20181029_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={'ordering': ('-created',), 'permissions': (('can_access_partnerships', 'can_access_partnerships'),)},
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, help_text='media_file_or_url', null=True, upload_to='partnerships/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('EPLUS-EDU-HEI', 'Higher education institution (tertiary level)'), ('EPLUS-EDU-GEN-PRE', 'School/Institute/Educational centre – General education (pre-primary level)'), ('EPLUS-EDU-GEN-PRI', 'School/Institute/Educational centre – General education (primary level)'), ('EPLUS-EDU-GEN-SEC', 'School/Institute/Educational centre – General education (secondary level)'), ('EPLUS-EDU-VOC-SEC', 'School/Institute/Educational centre – Vocational Training (secondary level)'), ('EPLUS-EDU-VOC-TER', 'School/Institute/Educational centre – Vocational Training (tertiary level)'), ('EPLUS-EDU-ADULT', 'School/Institute/Educational centre – Adult education'), ('EPLUS-BODY-PUB-NAT', 'National Public body'), ('EPLUS-BODY-PUB-REG', 'Regional Public body'), ('EPLUS-BODY-PUB-LOC', 'Local Public body'), ('EPLUS-ENT-SME', 'Small and medium sized enterprise'), ('EPLUS-ENT-LARGE', 'Large enterprise'), ('EPLUS-NGO', 'Non-governmental organisation/association/social enterprise'), ('EPLUS-FOUND', 'Foundation'), ('EPLUS-SOCIAL', 'Social partner or other representative of working life (chambers of commerce, trade union, trade association)'), ('EPLUS-RES', 'Research Institute/Centre'), ('EPLUS-YOUTH-COUNCIL', 'National Youth Council'), ('EPLUS-ENGO', 'European NGO'), ('EPLUS-NET-EU', 'EU-wide network'), ('EPLUS-YOUTH-GROUP', 'Group of young people active in youth work'), ('EPLUS-EURO-GROUP-COOP', 'European grouping of territorial cooperation'), ('EPLUS-BODY-ACCRED', 'Accreditation, _(certification or qualification body'), ('EPLUS-BODY-CONS', 'Counsellzing body'), ('EPLUS-INTER', 'International organisation under public law'), ('EPLUS-SPORT-PARTIAL', 'Organisation or association representing (parts of) the sport sector'), ('EPLUS-SPORT-FED', 'Sport federation'), ('EPLUS-SPORT-LEAGUE', 'Sport league'), ('EPLUS-SPORT-CLUB', 'Sport club'), ('OTH', 'Other')], help_text='mandatory_if_not_pic_ies', max_length=255, null=True, verbose_name='partner_contact_type'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='education_levels',
            field=models.ManyToManyField(blank=True, related_name='partnerships_years', to='partnership.PartnershipYearEducationLevel', verbose_name='partnership_year_education_levels'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text='partnership_year_entities_help_text', related_name='partnerships_years', to='base.Entity', verbose_name='partnership_year_entities'),
        ),
        migrations.AlterField(
            model_name='uclmanagemententity',
            name='academic_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_entities', to='base.Person', verbose_name='academic_responsible'),
        ),
        migrations.RunPython(remove_unused_permissions, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
