# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0037_auto_20181106_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershipagreement',
            name='eligible',
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='eligible',
            field=models.BooleanField(default=True, verbose_name='eligible'),
        ),
    ]
