# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0038_auto_20181207_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershipagreement',
            options={'ordering': ['-start_academic_year__start_date'], 'permissions': (('can_access_partnerships_agreements', 'can_access_partnerships_agreements'),), 'verbose_name': 'financing'},
        ),
        migrations.AddField(
            model_name='partner',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='partnershipyeareducationfield',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
