# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0039_auto_20190404_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfiguration',
            name='partnership_api_max_date_day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=31, verbose_name='partnership_api_max_date_day'),
        ),
        migrations.AddField(
            model_name='partnershipconfiguration',
            name='partnership_api_max_date_month',
            field=models.IntegerField(choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], default=12, verbose_name='partnership_api_max_date_month'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='is_smst',
            field=models.BooleanField(default=False, verbose_name='is_smst'),
        ),
    ]
