# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 15:18
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def init_partnership_uuid(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    for partnership in Partnership.objects.all():
        partnership.uuid = uuid.uuid4()
        partnership.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0040_auto_20190409_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(init_partnership_uuid, reverse_code=migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='partnership',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
