# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0041_partnership_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='_partnership_medias_+', to='partnership.Media', verbose_name='medias'),
        ),
    ]
