# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 16:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0043_auto_20190523_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='code')),
                ('label', models.CharField(max_length=250, verbose_name='label')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='is_visible_in_portal',
            field=models.BooleanField(default=True, verbose_name='is_visible_in_portal'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partnership.MediaType', verbose_name='type'),
        ),
    ]
