# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def init_media_uuid(apps, schema_editor):
    Media = apps.get_model('partnership', 'Media')
    for media in Media.objects.all():
        media.uuid = uuid.uuid4()
        media.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0044_auto_20190524_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(init_media_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='media',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
