# Generated by Django 2.2.5 on 2020-01-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0044_auto_20190524_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='external_id',
            field=models.CharField(blank=True, editable=False, help_text='to_synchronize_with_epc', max_length=255, null=True, unique=True, verbose_name='external_id'),
        ),
    ]
