# Generated by Django 2.2.5 on 2020-02-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0045_auto_20200129_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_visible_in_portal',
            field=models.BooleanField(blank=True, default=True, verbose_name='is_visible_in_portal'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='ucl_university',
            field=models.ForeignKey(limit_choices_to={'entityversion__entity_type': 'FACULTY', 'faculty_managements__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships', to='base.Entity', verbose_name='ucl_university'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='ucl_university_labo',
            field=models.ForeignKey(blank=True, limit_choices_to={'entity_managements__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_labo', to='base.Entity', verbose_name='ucl_university_labo'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='eligible',
            field=models.BooleanField(blank=True, default=True, verbose_name='eligible'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='is_smp',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_smp'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='is_sms',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_sms'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='is_smst',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_smst'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='is_sta',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_sta'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='is_stt',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_stt'),
        ),
    ]
