# Generated by Django 2.2.5 on 2020-02-18 10:29

from django.db import migrations, models, connection
import django.db.models.deletion


def link_author_person(apps, schema_editor):
    Person = apps.get_model('base', 'Person')
    Media = apps.get_model('partnership', 'Media')
    Partner = apps.get_model('partnership', 'Partner')
    PartnerEntity = apps.get_model('partnership', 'PartnerEntity')
    Partnership = apps.get_model('partnership', 'Partnership')

    for model in [Media, Partner, PartnerEntity, Partnership]:
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE {} m SET new_author_id = p.id "
                "FROM {} p WHERE p.user_id = m.author_id".format(
                    model._meta.db_table, Person._meta.db_table
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0505_update_summary_submission_calendars'),
        ('partnership', '0046_auto_20200218_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='new_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.Person', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='partner',
            name='new_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.Person', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='partnerentity',
            name='new_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.Person', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='new_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.Person', verbose_name='author'),
        ),
        migrations.RunPython(
            link_author_person, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='media',
            name='author',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='author',
        ),
        migrations.RemoveField(
            model_name='partnerentity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='author',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='new_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='new_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='partnerentity',
            old_name='new_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='new_author',
            new_name='author',
        ),
    ]
