# Generated by Django 2.2.5 on 2020-03-24 16:09
from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    Configuration = apps.get_model('partnership', 'PartnershipConfiguration')
    AcademicYear = apps.get_model('base', 'AcademicYear')

    # Configuration.get_configuration() seems unavailable in migrations
    config = Configuration.objects.first()
    if config:
        config.partnership_api_year = AcademicYear.objects.filter(
            year=datetime.today().year,
        ).first()
        config.save()


def backward(apps, schema_editor):
    Configuration = apps.get_model('partnership', 'PartnershipConfiguration')

    # Configuration.get_configuration() seems unavailable in migrations
    config = Configuration.objects.first()
    if config and config.partnership_api_year:
        start_date = config.partnership_api_year.start_date
        config.partnership_api_max_date_day = start_date.day
        config.partnership_api_max_date_month = start_date.month
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0507_configuration_academic_year'),
        ('partnership', '0049_enums'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfiguration',
            name='partnership_api_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear', verbose_name='partnership_api_year'),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='partnershipconfiguration',
            name='partnership_api_max_date_day',
        ),
        migrations.RemoveField(
            model_name='partnershipconfiguration',
            name='partnership_api_max_date_month',
        ),
    ]
