# Generated by Django 2.2.10 on 2020-04-24 10:58

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F, OuterRef, Subquery


def forward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnershipYear = apps.get_model('partnership', 'PartnershipYear')

    Partnership.objects.annotate(
        type=Subquery(
            PartnershipYear.objects.filter(
                partnership=OuterRef('pk'),
            ).values('partnership_type')[:1]
        ),
    ).update(partnership_type=F('type'))


def backward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnershipYear = apps.get_model('partnership', 'PartnershipYear')

    PartnershipYear.objects.annotate(
        type=Subquery(
            Partnership.objects.filter(
                pk=OuterRef('partnership'),
            ).values('partnership_type')[:1]
        ),
    ).update(partnership_type=F('type'))


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0053_domain_isced_migration'),
    ]

    operations = [
        # Make both fields nullable
        migrations.AddField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[
                ('GENERAL', 'Accord général de collaboration'),
                ('MOBILITY', 'Partenariat de mobilité'),
                ('COURSE', 'Partenariat de co-organisation de formation'),
                ('DOCTORATE', 'Partenariat de co-organisation de doctorat'),
                ('PROJECT', 'Projet financé'),
            ], max_length=255, null=True, verbose_name='partnership_type'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='partnership_type',
            field=models.CharField(choices=[
                ('INTENTION', 'Déclaration d’intention'),
                ('CADRE', 'Accord-cadre'),
                ('SPECIFIQUE', 'Accord spécifique'),
                ('CODIPLOMATION', 'Accord de co-diplômation'),
                ('COTUTELLE', 'Accord de co-tutelle'),
                ('MOBILITY', 'Partenariat de mobilité'),
                ('FOND_APPUIE', 'Projet Fonds d’appuie à l’internationnalisation'),
                ('AUTRE', 'Autre'),
            ], max_length=255, null=True, verbose_name='partnership_type'),
        ),
        # Migrate data
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='partnershipyear',
            name='partnership_type',
        ),
        migrations.AlterField(
            model_name='partnership',
            name='ucl_entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='partnerships', to='base.Entity',
                verbose_name='ucl_entity'),
        ),
        # Make not nullable
        migrations.AlterField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[
                ('GENERAL', 'Accord général de collaboration'),
                ('MOBILITY', 'Partenariat de mobilité'),
                ('COURSE', 'Partenariat de co-organisation de formation'),
                ('DOCTORATE', 'Partenariat de co-organisation de doctorat'),
                ('PROJECT', 'Projet financé')
            ], max_length=255, verbose_name='partnership_type'),
        ),
    ]
