# Generated by Django 2.2.10 on 2020-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0054_move_partnership_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={
                'ordering': ('-created',),
                'permissions': (
                    ('can_access_partnerships', 'can_access_partnerships'),
                    ('change_GENERAL', 'can change GENERAL'),
                    ('change_MOBILITY', 'can change MOBILITY'),
                    ('change_COURSE', 'can change COURSE'),
                    ('change_DOCTORATE', 'can change DOCTORATE'),
                    ('change_PROJECT', 'can change PROJECT'),
                )
            },
        ),
    ]
