# Generated by Django 2.2.10 on 2020-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0055_osis_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, help_text='media_file_or_url', max_length=1000, null=True, verbose_name='url'),
        ),
    ]
