# Generated by Django 2.2.10 on 2020-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0055_create_type_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershipentitymanager',
            options={'verbose_name': 'Partnership manager', 'verbose_name_plural': 'Partnership managers'},
        ),
        migrations.AddField(
            model_name='partnershipentitymanager',
            name='with_child',
            field=models.BooleanField(default=False),
        ),
    ]
