# Generated by Django 2.2.10 on 2020-05-25 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0058_start_end_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('types', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        choices=[
                            ('GENERAL', 'Accord général de collaboration'),
                            ('MOBILITY', 'Partenariat de mobilité'),
                            ('COURSE', 'Partenariat de co-organisation de formation'),
                            ('DOCTORATE', 'Partenariat de co-organisation de doctorat'),
                            ('PROJECT', 'Projet financé'),
                        ],
                        max_length=50,
                    ),
                    size=None),
                ),
            ],
            options={
                'verbose_name': 'partnership_mission',
            },
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='missions',
            field=models.ManyToManyField(to='partnership.PartnershipMission'),
        ),
    ]
