# Generated by Django 2.2.10 on 2020-05-25 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0058_start_end_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipyear',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='partnership_year_description'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='id_number',
            field=models.CharField(default='', max_length=200, verbose_name='partnership_year_id_number'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='project_title',
            field=models.CharField(default='', max_length=200, verbose_name='partnership_year_project_title'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='ucl_status',
            field=models.CharField(
                choices=[
                    ('coordinator', 'Coordinator'),
                    ('partner', 'Partner'),
                ],
                default='',
                max_length=20,
                verbose_name='partnership_year_ucl_status',
            ),
        ),
        migrations.CreateModel(
            name='PartnershipMission',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('types', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        choices=[
                            ('GENERAL', 'Accord général de collaboration'),
                            ('MOBILITY', 'Partenariat de mobilité'),
                            ('COURSE', 'Partenariat de co-organisation de formation'),
                            ('DOCTORATE', 'Partenariat de co-organisation de doctorat'),
                            ('PROJECT', 'Projet financé'),
                        ],
                        max_length=50,
                    ),
                    size=None,
                )),
            ],
            options={
                'verbose_name': 'partnership_mission',
            },
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='missions',
            field=models.ManyToManyField(
                to='partnership.PartnershipMission',
                verbose_name='partnership_missions',
            ),
        ),
        migrations.CreateModel(
            name='PartnershipSubtype',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('types', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        choices=[
                            ('GENERAL', 'Accord général de collaboration'),
                            ('MOBILITY', 'Partenariat de mobilité'),
                            ('COURSE', 'Partenariat de co-organisation de formation'),
                            ('DOCTORATE', 'Partenariat de co-organisation de doctorat'),
                            ('PROJECT', 'Projet financé'),
                        ],
                        max_length=50,
                    ),
                    size=None,
                )),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'partnership_subtype',
            },
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='subtype',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='years',
                to='partnership.PartnershipSubtype',
                verbose_name='partnership_subtype',
            ),
        ),
    ]
