# Generated by Django 2.2.10 on 2020-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0059_subtype_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipagreement',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='partnershipagreement',
            name='start_date',
            field=models.DateField(null=True, verbose_name='start_date'),
        ),
    ]
