# Generated by Django 2.2.10 on 2020-06-22 10:33

from django.db import migrations
from django.db.models import OuterRef, Subquery

from partnership.models import PartnershipType


def forward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnershipYear = apps.get_model('partnership', 'PartnershipYear')
    Partnership.objects.filter(
        partnership_type__in=PartnershipType.with_synced_dates(),
    ).update(
        start_date=Subquery(
            PartnershipYear.objects.filter(
                partnership_id=OuterRef('pk'),
            ).order_by('academic_year__year').values('academic_year__start_date')[:1]
        ),
        end_date=Subquery(
            PartnershipYear.objects.filter(
                partnership_id=OuterRef('pk'),
            ).order_by('-academic_year__year').values('academic_year__end_date')[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0062_partnership_is_public'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
