# Generated by Django 2.2.10 on 2020-06-22 10:33

from django.db import migrations
from django.db.models import F, OuterRef, Subquery


def forward(apps, schema_editor):
    PartnershipAgreement = apps.get_model('partnership', 'PartnershipAgreement')
    AcademicYear = apps.get_model('base', 'AcademicYear')
    PartnershipAgreement.objects.update(
        start_date=Subquery(AcademicYear.objects.filter(
            pk=OuterRef('start_academic_year_id'),
        ).values('start_date')[:1]),
        end_date=Subquery(AcademicYear.objects.filter(
            pk=OuterRef('end_academic_year_id'),
        ).values('end_date')[:1]),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0064_create_default_mission_subtypes'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop, elidable=True)
    ]
