# Generated by Django 2.2.10 on 2020-06-10 15:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0067_migrate_partner_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_code',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
        migrations.DeleteModel(
            name='PartnerType',
        ),
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to='base.Organization',
            ),
        ),
    ]
