# Generated by Django 2.2.13 on 2020-07-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0068_remove_partner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipyear',
            name='funding_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='years', to='partnership.FundingProgram', verbose_name='funding_program'),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='years', to='partnership.FundingSource', verbose_name='funding_source'),
        ),
        migrations.AlterField(
            model_name='partnershipyear',
            name='funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='years', to='partnership.FundingType', verbose_name='funding_type'),
        ),
    ]
