# Generated by Django 2.2.13 on 2020-08-21 15:38
from django.db import migrations, models
from django.db.models import F


def forward(apps, schema_editor):
    PartnershipSubtype = apps.get_model('partnership', 'PartnershipSubtype')
    PartnershipSubtype.objects.update(order=F('pk'))


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0072_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipsubtype',
            name='order',
            field=models.PositiveIntegerField(
                db_index=True,
                null=True,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partnershipsubtype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='partnershipsubtype',
            options={
                'ordering': ('order',),
                'verbose_name': 'partnership_subtype',
            },
        ),
    ]
