# Generated by Django 2.2.13 on 2020-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0072_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(choices=[('GENERAL', 'Accord général de collaboration'), ('MOBILITY', 'Partenariat de mobilité'), ('COURSE', 'Partenariat de co-organisation de formation'), ('DOCTORATE', 'Partenariat de co-organisation de doctorat'), ('PROJECT', 'Projet financé')], db_index=True, max_length=255, verbose_name='partnership_type'),
        ),
    ]
