# Generated by Django 2.2.13 on 2020-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0075_partner_entity_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingprogram',
            options={'ordering': ('name',), 'verbose_name': 'funding_program'},
        ),
        migrations.AlterModelOptions(
            name='fundingsource',
            options={'ordering': ('name',), 'verbose_name': 'funding_source'},
        ),
        migrations.AlterModelOptions(
            name='fundingtype',
            options={'ordering': ('name',), 'verbose_name': 'funding_type'},
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
    ]
