# Generated by Django 2.2.13 on 2020-10-02 17:33

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Subquery, OuterRef, F


def forward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnerEntity = apps.get_model('partnership', 'PartnerEntity')
    Partnership.objects.filter(partner_entity_old__isnull=False).annotate(
        partner_entity_entity=Subquery(PartnerEntity.objects.filter(
            pk=OuterRef('partner_entity_old')
        ).values('entity_id')[:1])
    ).update(partner_entity_id=F('partner_entity_entity'))


def backward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnerEntity = apps.get_model('partnership', 'PartnerEntity')
    Partnership.objects.annotate(
        partner_entity_new=Subquery(PartnerEntity.objects.filter(
            entity_id=OuterRef('partner_entity_id')
        ).values('pk')[:1])
    ).update(partner_entity_old_id=F('partner_entity_new'))


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0076_auto_20200925_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='partner_entity',
            new_name='partner_entity_old',
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner_entity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='partner_of',
                to='base.Entity',
                verbose_name='partner_entity',
            ),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='partnership',
            name='partner_entity_old',
        ),
    ]
