# Generated by Django 2.2.13 on 2021-01-11 14:33

from django.db import migrations


def remove_partnership_year_education_level(apps, schema_editor):
    PartnershipYearEducationLevel = apps.get_model('partnership', 'PartnershipYearEducationLevel')
    PartnershipYearEducationLevel.objects.filter(code="ISCED-5").delete()
    PartnershipYearEducationLevel.objects.filter(code="ISCED-9").delete()


def create_partnership_year_education_level(apps, schema_editor):
    PartnershipYearEducationLevel = apps.get_model('partnership', 'PartnershipYearEducationLevel')
    PartnershipYearEducationLevel.objects.update_or_create(
        code="ISCED-5",
        defaults={
            'label': "Short cycle within the first cycle / Short-cycle tertiary education (EQF-5)"
        }
    )
    PartnershipYearEducationLevel.objects.update_or_create(
        code="ISCED-9",
        defaults={
            'label': "Not elsewhere classified"
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0082_funding_is_active'),
    ]

    operations = [
        migrations.RunPython(remove_partnership_year_education_level, create_partnership_year_education_level)
    ]
