# Generated by Django 2.2.13 on 2021-02-22 11:08
from django.db import migrations
from django.db.models import F, Subquery, OuterRef

from base.models.enums.organization_type import MAIN
from partnership.utils import generate_partner_prefix, generate_unique_acronym


def forward(apps, schema_editor):
    Organization = apps.get_model('base', 'Organization')
    EntityVersion = apps.get_model('base', 'EntityVersion')

    # Set all missing acronyms on organizations
    missing_acronym = Organization.objects.filter(
        prefix="",
        partner__isnull=False,
    ).exclude(type=MAIN).order_by('name')
    existing_acronyms = list(Organization.objects.exclude(
        prefix="",
    ).order_by('prefix').distinct('prefix').values_list('prefix', flat=True))

    for org in missing_acronym:
        org.prefix = generate_partner_prefix(org.name, existing_acronyms)
        existing_acronyms.append(org.prefix)

    Organization.objects.bulk_update(missing_acronym, ['prefix'])

    # Update all acronyms for root entityversions
    # -- somehow a simple update won't work, so doing a bulk update
    versions = EntityVersion.objects.annotate(
        org_acronym=Subquery(Organization.objects.filter(
            pk=OuterRef('entity__organization_id')
        ).order_by('name').values('prefix'))
    ).filter(
        entity__organization__partner__isnull=False,
        parent__isnull=True,
    ).exclude(
        entity__organization__type=MAIN,
        acronym=F('org_acronym')
    )

    for version in versions:
        version.acronym = version.org_acronym

    EntityVersion.objects.bulk_update(versions, ['acronym'])

    # Update all acronyms for entityversions of subentities
    sub_versions = EntityVersion.objects.annotate(
        org_acronym=Subquery(Organization.objects.filter(
            pk=OuterRef('entity__organization_id')
        ).order_by('name').values('prefix'))
    ).filter(
        entity__organization__partner__isnull=False,
        parent__isnull=False,
    ).exclude(
        entity__organization__type=MAIN,
    )
    acronym_mapping = {}
    for sub_version in sub_versions:
        sub_version.acronym = acronym_mapping.get(
            sub_version.entity_id,
            generate_unique_acronym(sub_version.org_acronym, existing=existing_acronyms)
        )
        if sub_version.acronym not in existing_acronyms:
            existing_acronyms.append(sub_version.acronym)
    EntityVersion.objects.bulk_update(sub_versions, ['acronym'])


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0083_auto_20210111_1433'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop, elidable=True)
    ]
