# Generated by Django 2.2.13 on 2021-03-31 14:56
from datetime import timedelta

from django.db import migrations, connection

from base.utils.db import dict_fetchall


def forward(apps, schema_editor):
    EntityVersion = apps.get_model('base', 'EntityVersion')
    with connection.cursor() as cursor:
        cursor.execute('''
            select distinct ent_ver1.id as ver1_id,
                    ent_ver2.start_date
            from base_entity ent
                join base_organization org on org.id = ent.organization_id 
                    and org.type in ('ENTERPRISE', 'OTHER', 'ACADEMIC_PARTNER',
                                     'HOSPITAL', 'RESEARCH_CENTER', 'NGO')
                join base_entityversion ent_ver1 on ent_ver1.entity_id = ent.id
                join base_entityversion ent_ver2 on ent_ver2.entity_id = ent.id
            where ent_ver1.id != ent_ver2.id
              and ent_ver1.start_date < ent_ver2.start_date
              and (ent_ver1.end_date is null or ent_ver1.end_date >= ent_ver2.start_date)
            order by ver1_id;
        ''')
        for row in dict_fetchall(cursor):
            EntityVersion.objects.filter(
                pk=row['ver1_id'],
            ).update(end_date=row['start_date'] - timedelta(days=1))


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0085_drop_partner_relation'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
