# Generated by Django 2.2.13 on 2021-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0572_auto_20210309_1616'),
        ('partnership', '0086_fix_end_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.entity',),
        ),
    ]
