# Generated by Django 2.2.13 on 2021-03-10 15:18
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnershipPartnerRelation = apps.get_model('partnership', 'PartnershipPartnerRelation')
    mapping = dict(Partnership.objects.values_list('pk', 'partner_entity_id'))

    instances = []
    for partnership_id, partner_entity_id in mapping.items():
        instances.append(PartnershipPartnerRelation(
            partnership_id=partnership_id,
            entity_id=partner_entity_id,
        ))
    PartnershipPartnerRelation.objects.bulk_create(instances)


def backwards(apps, schema_editor):
    Partnership = apps.get_model('partnership', 'Partnership')
    PartnershipPartnerRelation = apps.get_model('partnership', 'PartnershipPartnerRelation')
    Partnership.objects.annotate(
        partnerentityid=models.Subquery(PartnershipPartnerRelation.objects.filter(
            partnership_id=models.OuterRef('pk'),
        ).values('entity_id')[:1])
    ).update(partner_entity_id=models.F('partnerentityid'))


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0572_auto_20210309_1616'),
        ('partnership', '0087_entity_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='partner_entity',
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name='partner_of',
                to='base.Entity',
                verbose_name='partner_entity',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='PartnershipPartnerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_of', to='base.Entity')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.Partnership')),
            ],
            options={
                'unique_together': {('partnership', 'entity')},
            },
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner_entities',
            field=models.ManyToManyField(through='partnership.PartnershipPartnerRelation', to='base.Entity', verbose_name='partner_entities'),
        ),
        migrations.RunPython(forward, backwards),
        migrations.RemoveField(
            model_name='partnership',
            name='partner_entity',
        ),
        migrations.AlterModelOptions(
            name='partnership',
            options={
                'base_manager_name': 'objects',
                'ordering': ('-created',),
                'permissions': (
                     ('can_access_partnerships', 'can_access_partnerships'),
                ),
            },
        ),
        migrations.AddField(
            model_name='partnership',
            name='project_acronym',
            field=models.CharField(
                default='',
                max_length=20,
                verbose_name='partnership_project_acronym',
                blank=True,
            ),
        ),
    ]
