# Generated by Django 2.2.13 on 2021-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0088_partnership_partner_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='project_acronym',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='partnership_project_acronym'),
        ),
    ]
