# Generated by Django 2.2.13 on 2021-05-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0089_increase_acronym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_ies',
        ),
    ]
