# Generated by Django 4.2.20 on 2025-03-31 15:51

from django.db import migrations, models


def initialize_flow_direction(apps, schema_editor):
    PartnershipYear = apps.get_model('partnership', 'PartnershipYear')
    PartnershipYear.objects.filter(eligible=False).update(flow_direction="IN")


class Migration(migrations.Migration):

    dependencies = [
        ("partnership", "0092_copy_partner_address_to_new_version"),
        ("partnership", "0012_auto_20250414_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershipyear",
            name="flow_direction",
            field=models.CharField(
                choices=[("IN", "IN"), ("OUT", "OUT"), ("IN_OUT", "IN/OUT")],
                default="IN_OUT",
                max_length=20,
                verbose_name="Partnership flow direction",
            ),
        ),
        migrations.RunPython(initialize_flow_direction, reverse_code=migrations.RunPython.noop),
    ]
