# Generated by Django 4.2.20 on 2025-04-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0012_auto_20250414_1138'),
        ('partnership', '0093_partnershipyear_flow_direction'),
    ]

    operations = [
    ]
