# Generated by Django 4.2.20 on 2025-04-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0094_merge_20250415_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipyearoffers',
            name='educationgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_educationgroup', to='base.educationgroup', verbose_name='education_group'),
        ),
    ]
