# Generated by Django 4.2.20 on 2025-04-29 09:42
from django.conf import settings
from django.db import migrations


def add_education_group_type_fie(apps, schema_editor):
    if settings.TESTING:
        return

    # Add group type FIE MASTER_M et MASTER_M5
    EducationGroupType = apps.get_model("base", "EducationGroupType")
    PartnershipYearEducationLevel = apps.get_model("partnership", "PartnershipYearEducationLevel")

    m4_type = EducationGroupType.objects.get(
        category='TRAINING',
        name='MASTER_M4',
    )

    m5_type = EducationGroupType.objects.get(
        category='TRAINING',
        name='MASTER_M5',
    )

    isced_master = PartnershipYearEducationLevel.objects.filter(code='ISCED-7')
    if isced_master.exists():
        isced_master.first().education_group_types.add(m4_type)
        isced_master.first().education_group_types.add(m5_type)
        isced_master.first().save()

    # Change label/field subtype of partnership
    PartnershipSubtype = apps.get_model("partnership", "PartnershipSubtype")

    other_diplomation = PartnershipSubtype.objects.filter(
        code='OTHER_DI'
    )
    if other_diplomation.exists():
        other_diplomation.first().label="autre collaboration pour la diplomation"
        other_diplomation.first().save()

class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0095_alter_partnershipyearoffers_educationgroup'),
    ]

    operations = [
        migrations.RunPython(add_education_group_type_fie, ),
    ]
