# Generated by Django 4.2.20 on 2025-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0096_auto_20250429_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershippartnerrelationyear',
            name='all_student',
            field=models.BooleanField(blank=True, default=True, verbose_name='all_student'),
        ),
    ]
