# Generated by Django 4.2.20 on 2025-05-13 11:27
from django.db import migrations
from django.conf import settings


def upadte_education_group_year_field_isced(apps, schema_editor):
    """Update the isced field in table base_education_group_year.
    This migration is done to prevent errors for the co-roganization migration in the partnership module."""
    if settings.TESTING:
        return

    dictionnary = {
        "ALIT2MC": "0721",
        "ARGD2MC": "0222",
        "CAEM2MS/G": "0414",
        "COAM2MS/G": "0414",
        "COMB2MA": "0414",
        "CYSE2MS": "0612",
        "CYSE2MS/CA": "0612",
        "CYSE2MS/SE": "0612",
        "EBEP2MC": "0311",
        "ECFA2MS/G": "0411",
        "ECON2M1": "0311",
        "ECOS2MC": "0388",
        "ECSO2MC": "0311",
        "EUHD2MC": "0312",
        "EURO2MS": "0312",
        "EURO2MS/EM": "0312",
        "EURO2MS/PE": "0312",
        "GENT2MS/G": "0413",
        "MAJV2MS/GI": "0613",
        "MSFE2MC": "0114",
        "NEEA2MC": "0521",
        "NUTR2MC": "0915",
        "PRIS2MS/G": "0321",
        "REAU2MC": "0712",
        "RURA2MS": "0899",
        "RURA2MS/AG": "0899",
        "RURA2MS/DP": "0899",
        "RURA2MS/EM": "0899",
        "RURA2MS/MT": "0899",
        "RURA2MS/NC": "0899",
        "SDEV2MC": "0919",
        "TIS2MS/G": "0923",
        "TNIC1BA": "0414",
        "TRAM2MC": "0413",
        "TROP2MC": "0522"
    }

    EducationGroupYear = apps.get_model("base", "EducationGroupYear")
    DomainIsced = apps.get_model("reference", "DomainIsced")

    for key_dict in dictionnary:
        objs_egy = EducationGroupYear.objects.filter(acronym=key_dict)
        if objs_egy.exists():
            for obj_egy in objs_egy:
                if not obj_egy.isced_domain:
                    value_dict = dictionnary.get(key_dict)
                    obj_domain_isced = DomainIsced.objects.get(code=value_dict)
                    if obj_domain_isced:
                        obj_egy.isced_domain = obj_domain_isced
                        obj_egy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0097_partnershippartnerrelationyear_all_student')
    ]

    operations = [
        migrations.RunPython(code=upadte_education_group_year_field_isced, reverse_code=migrations.RunPython.noop, elidable=True),
    ]

