# Generated by Django 4.2.20 on 2025-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0098_auto_20250527_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershippartnerrelationyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
