# Generated by Django 4.2.20 on 2025-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0099_partnershippartnerrelationyear_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershippartnerrelation',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipyearoffers',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
