# Generated by Django 4.2.20 on 2025-08-11 11:48
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0100_partnership_changed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershippartnerrelationyear',
            name='external_id',
        ),
        migrations.AddField(
            model_name='partnershipyearoffers',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
