# Generated by Django 4.2.20 on 2025-08-11 11:48
from django.conf import settings
from django.db import migrations, models



def create_external_id(apps, schema_editor):
    """
        Migration to import historical data from base_organization into the partnerhsip module
    """
    if settings.TESTING:
        return
    PartnershipYearOffers = apps.get_model("partnership", "PartnershipYearOffers")
    for partnership_year_offers in PartnershipYearOffers.objects.all():
        partner_year = partnership_year_offers.partnershipyear
        partnership_year_offers.external_id = f"osis.partnershipyear_offers_{partner_year.external_id.split('_')[-1]}"
        partnership_year_offers.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0100_partnership_changed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershippartnerrelationyear',
            name='external_id',
        ),
        migrations.AddField(
            model_name='partnershipyearoffers',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.RunPython(code=create_external_id),
    ]
