# Generated by Django 4.2.20 on 2025-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0101_remove_partnershippartnerrelationyear_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershipyearoffers',
            name='external_id',
        ),
        migrations.AddField(
            model_name='partnershippartnerrelationyear',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
